// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA66ECsA9_24FWkYCld5Zc5YPY63ZS930',
    appId: '1:348847308893:web:ce7071d2bbd52f3d228db4',
    messagingSenderId: '348847308893',
    projectId: 'vhireapp',
    authDomain: 'vhireapp.firebaseapp.com',
    storageBucket: 'vhireapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkSpa-AYnYqnWayS3oBLgafMlOIdhJaEY',
    appId: '1:348847308893:android:53a40edbf6e6e5c9228db4',
    messagingSenderId: '348847308893',
    projectId: 'vhireapp',
    storageBucket: 'vhireapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd1qHF3DfdofgepHg05ItR2pLxRBX21sw',
    appId: '1:348847308893:ios:e2e667b56a71221a228db4',
    messagingSenderId: '348847308893',
    projectId: 'vhireapp',
    storageBucket: 'vhireapp.appspot.com',
    iosBundleId: 'io.vhire.vhireapp',
  );
}
